### ISSUE TITLE
gst-plugins-bad cannot use nvcodec by default

### ISSUE THREAD

**Issue by jian-lin** [NixOS/nixpkgs#189217]
### Describe the bug

gst-plugins-bad cannot use nvcodec by default. This can be verified in one of two ways:
- use `gst-inspect-1.0 nvcodec`. make sure you delete `~/.cache/gstreamer-1.0/registry.x86_64.bin` each time before running `gst-inspect-1.0`
  1. `nix shell nixpkgs#gst_all_1.gstreamer`
  2. set `GST_PLUGIN_SYSTEM_PATH_1_0` to `$(nix eval --raw nixpkgs#gst_all_1.gst-plugins-bad)/lib`
  3. `GST_DEBUG=2 gst-inspect-1.0 nvcodec`
  4. it says `nvcodec gstcudaloader.c:139:gst_cuda_load_library: Could not open library libcuda.so.1` and `0 features`. Here is the full output: [error.txt](https://github.com/NixOS/nixpkgs/files/9466479/error.txt)
- open `clapper`, a gstreamer based video player, and find that `nvcodec` is not in `Preference -> Tweaks -> Plugin Ranking`.

However, if I set `LD_LIBRARY_PATH` to `/run/opengl-driver/lib:$(nix eval --raw nixpkgs#cudatoolkit)/lib`:
- `GST_DEBUG=2 gst-inspect-1.0 nvcodec` says `18 features`. Full output is here:  [ok.txt](https://github.com/NixOS/nixpkgs/files/9466512/ok.txt)
- `clapper` can uses `nvcodec` to play videos 

### Additional context
I have tried to `addOpenGLRunpath` all libs of `gst_all_1.gst-plugins-bad`, but there is no difference and `LD_LIBRARY_PATH` is still needed.

### Notify maintainers
@jtojnar @jonringer who contribute to gst-plugins-bad
@samuela who is one of cuda maintainers
@tomfitzhenry who is clapper's maintainer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.61, NixOS, 22.11 (Raccoon), 22.11.20220829.3c51431`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/store/bpcyza9419m4zhxdqljf3giadw2ibgv4-source`
```

**Comment by jonringer** [comment]
> I have tried to addOpenGLRunpath all libs of gst_all_1.gst-plugins-bad, but there is no difference and LD_LIBRARY_PATH is still needed.

You need to do `addOpenGLRunpath` so that the plugins reference system drivers, and add:
```
hardware.opengl.extraPackages = [ cudatoolkit ];
```
to your configuration.nix, so that the cuda libraries exist on the system path (e.g. `/run/opengl-driver/lib`)

related: https://github.com/NixOS/rfcs/pull/121

**Comment by samuela** [comment]
I would recommend using [autoAddOpenGLRunpathHook](https://cs.github.com/?scopeName=All+repos&scope=&q=autoaddopenglrunpathhook) if at all possible. If there are elements of CUDA required as well those are available in `cudaPackages` and can be included as `buildInputs`. You can check out eg the derivation of jaxlib, pytorch, and others to see some examples!

**Comment by jonringer** [comment]
> I would recommend using [autoAddOpenGLRunpathHook](https://cs.github.com/?scopeName=All+repos&scope=&q=autoaddopenglrunpathhook)

I meant to mention the hook as well

**Comment by jonringer** [comment]
>  If there are elements of CUDA required as well those are available in cudaPackages and can be included as buildInputs. You can check out eg the derivation of jaxlib, pytorch, and others to see some examples!

Yes, but there will be times where software has optional nvidia capabilities, and we don't really want to add cuda to the build graph as it makes it: 1) unfree 2) bigger closure 3) only useful to nvidia users.

I think enabling the impure `opengl` route is the best compromise

**Comment by samuela** [comment]
> Yes, but there will be times where software has optional nvidia capabilities, and we don't really want to add cuda to the build graph as it makes it: 1) unfree 2) bigger closure 3) only useful to nvidia users.

Mmm, I see. What is your take on the current pattern of adding a build argument like `enableCuda` which defaults to false but allows users to override? For ML packages, we have a pattern of keeping both eg `jaxlib` and `jaxlibWithCuda` so that end users can choose between the smaller, non-CUDA version and the larger, unfree, CUDA-enabled version.

Would that kind of pattern solve this problem?

**Comment by jonringer** [comment]
> Mmm, I see. What is your take on the current pattern of adding a build argument like enableCuda which defaults to false but allows users to override? For ML packages, we have a pattern of keeping both eg jaxlib and jaxlibWithCuda so that end users can choose between the smaller, non-CUDA version and the larger, unfree, CUDA-enabled version.

I think if cuda availability is critical for a use case, then having a cuda variant makes sense. But for gstreamer plugins, it's not critical, but a big QoL win if nvidia is available.

**Comment by samuela** [comment]
I see... My hesitation with adding CUDA into `/run/opengl-driver/lib` is two-fold
1. CUDA is a set of user-level libraries and utilities, so having it live next to drivers in a privileged directory is unusual. Furthermore, Nix already has well-established patterns for linking against user-level libraries between packages. Any deviation from those patterns must come from some overwhelming raison d'être.
2. Having two ways of accessing CUDA libraries -- one via standard nix derivation inputs, and a second via `/run/opengl-driver/lib` -- introduces complexity. In my experience, any time there are two ways to accomplish the same thing, there comes the inevitable ecosystem schism with some people choosing to do it one way, and others choosing to do it the other way. Inevitably, people start asking questions like "What is the correct way to do X?" and then we're stuck having to explain why multiple options exist and what the various tradeoffs are.

I don't want to stand in the way of making this change if this truly is a life-changing improvement, but I feel obligated to bring up the treachery that likely lies ahead with a two-acceptable-solutions state of the world.

**Comment by samuela** [comment]
> `enableCuda`

I also forgot to mention previously: we already have a nixpkgs-wide config flag, `config.cudaSupport`, for this sort of thing.

**Comment by jian-lin** [comment]
> You need to do addOpenGLRunpath autoAddOpenGLRunpathHook

@jonringer I forget to mention that cuda is not necessary, only add /run/opengl/lib to LD_LIBRARY_PATH is enough. I do not think autoAddOpenGLRunpathHook will make a different result.

**Comment by jonringer** [comment]
Ah, yea, to be completely honest, cuda is outside of my domain of expertise. But if just the nvidia drivers suffice then we should probably ensure that the gstreamer packages use the opengl path.

**Comment by Kiskae** [comment]
I tried to reproduce this, but on my machine `libcuda` gets loaded transitively by `ffmpeg` which already has the opengl path patched in.

It does run into trouble finding `libnvidia-encode` however:
>    131713:	find library=libnvidia-encode.so.1 [0]; searching
>    131713:	 search path=/nix/store/nw3xfg5xsklpnnwkk08cyck829dlnpyv-glib-2.72.3/lib		(RUNPATH from file /nix/store/283k5cck45kxvird9bak5lxr2iqg9rpb-gstreamer-1.20.3/libexec/gstreamer-1.0/gst-plugin-scanner)

Output:

> 0:00:00.230404239 138521      0x17e9150 WARN                   nvenc gstnvenc.c:878:gst_nvenc_load_library: Could not open library libnvidia-encode.so.1, libnvidia-encode.so.1: cannot open shared object file: No such file or directory> Plugin Details:
>   Name                     nvcodec
>   Description              GStreamer NVCODEC plugin
>   Filename                 /nix/store/wv4shmzxa69gr1i9mfp91kmqdffznynj-gst-plugins-bad-1.20.3/lib/gstreamer-1.0/libgstnvcodec.so
>   Version                  1.20.3
>   License                  LGPL
>   Source module            gst-plugins-bad
>   Source release date      2022-06-15
>   Binary package           GStreamer Bad Plug-ins source release
>   Origin URL               Unknown package origin
> 
>   cudadownload: CUDA downloader
>   cudaupload: CUDA uploader
>   nvh264dec: NVDEC h264 Video Decoder
>   nvh264sldec: NVDEC H.264 Stateless Decoder
>   nvjpegdec: NVDEC jpeg Video Decoder
>   nvmpeg2videodec: NVDEC mpeg2video Video Decoder
>   nvmpeg4videodec: NVDEC mpeg4video Video Decoder
>   nvmpegvideodec: NVDEC mpegvideo Video Decoder
>

**Comment by jian-lin** [comment]
I add this to `pkgs/development/libraries/gstreamer/bad/default.nix`:
```
postFixup = ''
  addOpenGLRunpath $(find $out -type f)
'';
```
and add this to `pkgs/development/libraries/gstreamer/core/default.nix`:
```
postFixup = ''
  addOpenGLRunpath $(find $out -type f)
  addOpenGLRunpath $(find $bin -type f)
'';
```

After building the system, I run this:
```bash
export GST_PLUGIN_SYSTEM_PATH_1_0=/nix/store/hash-gst-plugins-bad-1.20.1/lib
LD_DEBUG=libs GST_DEBUG=2 /nix/store/hash-gstreamer-1.20.1-bin/bin/gst-inspect-1.0 nvcodec
```

Here is the full log: [log.txt](https://github.com/NixOS/nixpkgs/files/9483774/log.txt)

The relevant part is:
```console
      9800:     find library=libcuda.so.1 [0]; searching
      9800:      search path=/nix/store/hwfw0q5plnqv7qqyz41i9jj9df5p556c-glib-2.72.3/lib                (RUNPATH from file /nix/store/gpg5pbkapbwl5s1210h1b77408ii6a3s-gstreamer-1.20.1/libexec/gstreamer-1.0/gst-plugin-scanner)
      9800:       trying file=/nix/store/hwfw0q5plnqv7qqyz41i9jj9df5p556c-glib-2.72.3/lib/libcuda.so.1
      9800:      search path=/nix/store/6f66prpgx1qx4n6k450sxs3d157ia1ps-glibc-2.35-163/lib             (system search path)
      9800:       trying file=/nix/store/6f66prpgx1qx4n6k450sxs3d157ia1ps-glibc-2.35-163/lib/libcuda.so.1
      9800:      search cache=/nix/store/6f66prpgx1qx4n6k450sxs3d157ia1ps-glibc-2.35-163/etc/ld.so.cache
      9800:      search path=/nix/store/6f66prpgx1qx4n6k450sxs3d157ia1ps-glibc-2.35-163/lib             (system search path)
      9800:       trying file=/nix/store/6f66prpgx1qx4n6k450sxs3d157ia1ps-glibc-2.35-163/lib/libcuda.so.1
      9800:     
0:00:00.042290579  9800       0xba9ea0 WARN                 nvcodec gstcudaloader.c:139:gst_cuda_load_library: Could not open library libcuda.so.1, libcuda.so.1: cannot open shared object file: No such file or directory
0:00:00.042295551  9800       0xba9ea0 WARN                 nvcodec plugin.c:73:plugin_init: Failed to load cuda library
```

However, before and after this part, the runpath of `/nix/store/gpg5pbkapbwl5s1210h1b77408ii6a3s-gstreamer-1.20.1/libexec/gstreamer-1.0/gst-plugin-scanner` does have `/run/opengl-driver/lib`.

**Comment by samuela** [comment]
I wonder if the `gst-plugin-scanner` binary is doing some weird hardcoding shenanigans that overrides RUNPATH... perhaps they only look in some set of "magic" locations on the user's system?

Not entirely sure how they would accomplish such a thing, but that's the only thing I can think of atm...

**Comment by Kiskae** [comment]
@samuela while reviewing the DL_DEBUG output, I noticed that the runpath is different every time a module is being loaded. I suspect that the runpath is actually coming from the `libgstXXXX.so` file and we're just running into a runtime limitation of `libdl`.

As a test, this is `libgstopenaptx` loading `libfreeaptx`:

>     131713:	find library=libfreeaptx.so.0 [0]; searching
>     131713:	 search path=/nix/store/nw3xfg5xsklpnnwkk08cyck829dlnpyv-glib-2.72.3/lib:/nix/store/283k5cck45kxvird9bak5lxr2iqg9rpb-gstreamer-1.20.3/lib:/nix/store/bisx9c9h9pzplbi94xck05qlkdamxy3c-gst-plugins-base-1.20.3/lib:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/glibc-hwcaps/x86-64-v2:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/tls/x86_64/x86_64:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/tls/x86_64:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/tls/x86_64:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/tls:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/x86_64/x86_64:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/x86_64:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib/x86_64:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib		(RUNPATH from file /nix/store/283k5cck45kxvird9bak5lxr2iqg9rpb-gstreamer-1.20.3/libexec/gstreamer-1.0/gst-plugin-scanner)

And this is the rpath of `lib/gstreamer-1.0/libgstopenaptx.so`:
`/nix/store/nw3xfg5xsklpnnwkk08cyck829dlnpyv-glib-2.72.3/lib:/nix/store/283k5cck45kxvird9bak5lxr2iqg9rpb-gstreamer-1.20.3/lib:/nix/store/bisx9c9h9pzplbi94xck05qlkdamxy3c-gst-plugins-base-1.20.3/lib:/nix/store/8bxcpgjj3ivjvz82r1igir5gnw0w9zgi-libfreeaptx-0.1.1/lib:/nix/store/fz54faknl123dimzz6jsppw193lx2mip-glibc-2.35-163/lib`

This leads me to believe that it might be fixable by changing the rpath of `libgstnvcodec`.

**Comment by jian-lin** [comment]
> This leads me to believe that it might be fixable by changing the rpath of libgstnvcodec.

If you mean RUNPATH by rpath, then the answer is no. I `addOpenGLRunpath` lingstnvcodec.so when I `addOpenGLRunpath` all libs of gst-plugins-bad.

The changes of RUNPATH in the log do look weird.

**Comment by Kiskae** [comment]
Google fished up https://github.com/NixOS/nixpkgs/issues/14164 which appears to be the exact same issue. It appears that the gmodule loading code really doesn't play very nice with RUNPATH patching and was historically fixed by changing the source code to open the absolute path, rather than the relative file.

**Comment by jian-lin** [comment]
> A better solution might be to attempt to load <driverLink>/lib/library.so first, and falling back to loading library.so if that fails.

I suggest the reverse loading order, i.e. loading library.so first and failing back to <driverLink>/lib/library.so, which is useful if people want to use a different library.so by setting `LD_LIBRARY_PATH`.

Do you think this is the right thing to do to solve this issue? If so, I can write a patch if no one is faster than me.

**Comment by Kiskae** [comment]
I was already in the process of making that change, its in the PR above

**Comment by Kiskae** [comment]
This should be fixed through the merging of #190023

**Comment by jian-lin** [comment]
This issue will be automatically closed when that pr reaches the master branch.

**Comment by jian-lin** [comment]
It seems that pr has [reached][1] the master branch. Not sure why this issue is not automatically closed.

Closing.

[1]: https://nixpk.gs/pr-tracker.html?pr=190023
