### ISSUE TITLE
python3Packages.bitsandbytes does not work with python3Packages.transformers

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#255230]
## Issue description
A popular usage pattern of the bitsandbytes library is via the transformers package. See eg [this blog post](https://github.com/huggingface/blog/blob/main/4bit-transformers-bitsandbytes.md).

This usage is not working in nixpkgs, however. I suspect other bitsandbytes usages may be broken as well.

The causative failure from the logs appears to be 
```
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118_nocublaslt.so. Maybe you need to compile it from source?
```

cc @bcdarwin @NixOS/cuda-maintainers 

### Steps to reproduce
Create a `shell.nix` with
```nix
let
  # Last updated: 2023-09-14. Check for new commits at https://status.nixos.org.
  pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/1697b7d480449b01111e352021f46e5879e47643.tar.gz") {
    config.allowUnfree = true;
    config.cudaSupport = true;
  };
in
pkgs.mkShell {
  buildInputs = with pkgs; [
    python3
    python3Packages.accelerate
    python3Packages.bitsandbytes
    python3Packages.transformers
  ];
}
```
and then run
```
nix-shell --run "nixGL python3 -c 'from transformers import AutoModelForCausalLM; model = AutoModelForCausalLM.from_pretrained(\"gpt2\", load_in_4bit=True, device_map=\"auto\")'"
```

<details><summary>Full failure log</summary>
<p>

```
❯ ns --run "nixGL python3 -c 'from transformers import AutoModelForCausalLM; model = AutoModelForCausalLM.from_pretrained(\"gpt2\", load_in_4bit=True, device_map=\"auto\")'"
False

===================================BUG REPORT===================================
/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /nix/store/as57ja6jw950q57lk3l24dx5zgvys5vx-libglvnd-1.6.0/lib:/nix/store/2pl7kgy9sl8rma6n72ym6vdgd2pmr4qa-nvidia-x11-525.60.13-nixGL/lib:/nix/store/7iv0f3kg3gx0hfxxyj0f236hgb4z5rxn-nvidia-x11-525.60.13-nixGL-lib32/lib:/nix/store/my0wqhd5212mkl3pqk12zqzlh5sifczb-libglvnd-1.6.0/lib did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default /home/sam.ainsworth/.nix-profile')}
The following directories listed in your path were found to be non-existent: {PosixPath('8200'), PosixPath('https'), PosixPath('//vault.robot.car')}
The following directories listed in your path were found to be non-existent: {PosixPath(' -frandom-seed=kkpdgn5f5f -isystem /nix/store/z3g9q6vl64a8qkbk277wslqmgbbg0hgw-protobuf-3.24.2/include -isystem /nix/store/djhrsj3mdmg6wvarxrshsj1iy0b2sy68-abseil-cpp-20230125.3/include -isystem /nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12/include -isystem /nix/store/4zw1fd92qwvbqcn5ilqsi2v2rxvkagwl-python3.10-torch-2.0.1-dev/include -isystem /nix/store/hbmmiw49vdg13fh519iv3szc7lwabqrr-krb5-1.20.1-dev/include -isystem /nix/store/z3g9q6vl64a8qkbk277wslqmgbbg0hgw-protobuf-3.24.2/include -isystem /nix/store/djhrsj3mdmg6wvarxrshsj1iy0b2sy68-abseil-cpp-20230125.3/include -isystem /nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12/include -isystem /nix/store/4zw1fd92qwvbqcn5ilqsi2v2rxvkagwl-python3.10-torch-2.0.1-dev/include -isystem /nix/store/hbmmiw49vdg13fh519iv3szc7lwabqrr-krb5-1.20.1-dev/include')}
The following directories listed in your path were found to be non-existent: {PosixPath('/nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12 /nix/store/dgbs8qb081wlsh9hrrywff14zp15zil9-python3.10-accelerate-0.21.0 /nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0 /nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0')}
The following directories listed in your path were found to be non-existent: {PosixPath('/nix/store/kkpdgn5f5f8api5kr0mgca329cpz61lm-nix-shell')}
The following directories listed in your path were found to be non-existent: {PosixPath('-rpath /nix/store/kkpdgn5f5f8api5kr0mgca329cpz61lm-nix-shell/lib  -L/nix/store/z3g9q6vl64a8qkbk277wslqmgbbg0hgw-protobuf-3.24.2/lib -L/nix/store/djhrsj3mdmg6wvarxrshsj1iy0b2sy68-abseil-cpp-20230125.3/lib -L/nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12/lib -L/nix/store/c5fwbkpkkqb0y6bp3laj70bhgys29f19-python3.10-torch-2.0.1-lib/lib -L/nix/store/fxrc8215gvl6mqpfn41i93qxgby8xzhp-krb5-1.20.1/lib -L/nix/store/z3g9q6vl64a8qkbk277wslqmgbbg0hgw-protobuf-3.24.2/lib -L/nix/store/djhrsj3mdmg6wvarxrshsj1iy0b2sy68-abseil-cpp-20230125.3/lib -L/nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12/lib -L/nix/store/c5fwbkpkkqb0y6bp3laj70bhgys29f19-python3.10-torch-2.0.1-lib/lib -L/nix/store/fxrc8215gvl6mqpfn41i93qxgby8xzhp-krb5-1.20.1/lib')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/nix/store/3423rb2jn5pms3czw7wb1wpi3kqk4vkz-cuda-native-redist-11.8/lib/libcudart.so'), PosixPath('/nix/store/3423rb2jn5pms3czw7wb1wpi3kqk4vkz-cuda-native-redist-11.8/lib/libcudart.so.11.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
DEBUG: Possible options found for libcudart.so: {PosixPath('/nix/store/3423rb2jn5pms3czw7wb1wpi3kqk4vkz-cuda-native-redist-11.8/lib/libcudart.so'), PosixPath('/nix/store/3423rb2jn5pms3czw7wb1wpi3kqk4vkz-cuda-native-redist-11.8/lib/libcudart.so.11.0')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1099, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/nix/store/vagb0sjv83ybi435i6iiv10hjrdghph9-python3-3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 38, in <module>
    from ...modeling_utils import PreTrainedModel, SequenceSummary
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/modeling_utils.py", line 86, in <module>
    from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
  File "/nix/store/dgbs8qb081wlsh9hrrywff14zp15zil9-python3.10-accelerate-0.21.0/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/nix/store/dgbs8qb081wlsh9hrrywff14zp15zil9-python3.10-accelerate-0.21.0/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/nix/store/dgbs8qb081wlsh9hrrywff14zp15zil9-python3.10-accelerate-0.21.0/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/nix/store/dgbs8qb081wlsh9hrrywff14zp15zil9-python3.10-accelerate-0.21.0/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/nix/store/dgbs8qb081wlsh9hrrywff14zp15zil9-python3.10-accelerate-0.21.0/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/nix/store/8ymak99z98mb7rkmn4galzhv4icfg09a-python3.10-bitsandbytes-0.41.0/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 492, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 376, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 666, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 680, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 625, in getattribute_from_module
    if hasattr(module, attr):
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1089, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/nix/store/36g42ndrx7i6889cy1pyl9w8rk9l7ymk-python3.10-transformers-4.31.0/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1101, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

</p>
</details> 

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1041-gcp, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.16.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by bcdarwin** [comment]
Thanks.  It was working for me with `transformers` before the last version bump, so it might have broken at that time or later.  I'll take a look sometime but not sure it will be in the next week.
