### ISSUE TITLE
cudatoolkit: Split output breaks inflexible build systems (TensorFlow)

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#29575]
## Issue description

bb1c9b027d343f2ce263496582d6b56af8af92e6 moved `libcudart.so` into a separate derivation output. This is troublesome for inflexible build systems that expect to find CUDA artifacts relative to a single path (typically the `nvcc` install path). Specifically, TensorFlow's rather arcane build system expects to be fed a single `CUDA_HOME` environment variable, and locates all CUDA artifacts from there.

I'd imagine such a predicament isn't unique to the CUDA ecosystem and might occur with multiple-output derivations in general. As a crude workaround my TensorFlow derivation has something like the following:

```
let unsplit_cudatoolkit = cudatoolkit.overrideAttrs (a : rec
    {
        outputs = ["out" "doc"];
        installPhase = ''
            export lib=$out
        '' + a.installPhase;
    });
```

Is there a more idiomatic way to "reunify" multiple-output derivations? Or are derivations downstream expected to be sufficiently flexible to deal with such things?

**Comment by FRidh** [comment]
How about merging the different outputs together with [`symlinkJoin`](https://github.com/NixOS/nixpkgs/blob/ad16a82b83555bb73acc899d9dd66a9241ce5f05/pkgs/build-support/trivial-builders.nix#L76)?

**Comment by FRidh** [comment]
@vcunat, is there any "preferred" method for unifying outputs?

**Comment by vcunat** [comment]
I certainly used `buildEnv` in at least one occasion (`libxml2Python`, still there); I expect `symlinkJoin` may cover a few more cases.  In some cases the builds don't even retain any reference to such unified trees.

**Comment by jyp** [comment]
Note that the split cudatoolkit does not work with pre-built tensorflow either. See #29798

**Comment by TravisWhitaker** [comment]
`symlinkJoin` does the trick nicely, thanks for the tip. Might be nice to add a note about it in the Nixpkgs manual section on multiple-output packages.

I think it makes sense to resume the TensorFlow discussion over at https://github.com/NixOS/nixpkgs/issues/29798
