### ISSUE TITLE
Python 3.6 tensorflowWithCuda cannot be imported due to being unable to find libcublas.so.8.0

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#31027]
## Issue description

When importing `import tensorflow as tf` in Python 36:

```
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
```

It does work in 17.03 python 35 (I later pinned to 17.03 channel and use python35).

```
{
  pkgs ? import <nixpkgs> {}
}:
  with pkgs;
  python36Packages.buildPythonApplication {
    name = "tensorstuff";
    buildInputs =  (with python36Packages; [
      tensorflowWithCuda
    ]);
  }
```

## Technical details

* System: 17.09.git.8fefa85
* Nix version: nix-env (Nix) 1.11.15
* Nixpkgs version: "17.09.git.8fefa85f5c"
* Sandboxing enabled: build-use-sandbox = true

**Comment by CMCDragonkai** [comment]
Also wanted to note that:

Using tensorflowWithCuda along with matplotlib results in this error when matplotlib is imported after tensorflow is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/mlz868r5mxpnfh4a8fh00xwscbpwniz5-python3.5-matplotlib-2.0.0/lib/python3.5/site-packages/matplotlib/pyplot.py", line 37, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/nix/store/mlz868r5mxpnfh4a8fh00xwscbpwniz5-python3.5-matplotlib-2.0.0/lib/python3.5/site-packages/matplotlib/figure.py", line 35, in <module>
    from matplotlib import image as mimage
  File "/nix/store/mlz868r5mxpnfh4a8fh00xwscbpwniz5-python3.5-matplotlib-2.0.0/lib/python3.5/site-packages/matplotlib/image.py", line 27, in <module>
    import matplotlib._image as _image
ImportError: /nix/store/i4kxa8abq1r1isy3kd73chi33nhmq0lv-gcc-4.9.4-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /nix/store/mlz868r5mxpnfh4a8fh00xwscbpwniz5-python3.5-matplotlib-2.0.0/lib/python3.5/site-packages/matplotlib/_image.cpython-35m-x86_64-linux-gnu.so)
```

In fact matplotlib doesn't appear to work with tensorflowWithCuda even if it is imported beforehand. I found this at 17.03 channel 630dbfe672164eeaf4bc822226cbb3ad7c1b0805.

**Comment by abbradar** [comment]
I think https://github.com/NixOS/nixpkgs/pull/31507 should fix this (it works for me now, I use a different way to link CUDA libraries).

**Comment by abbradar** [comment]
Should be fixed as #31507 is in.

**Comment by CMCDragonkai** [comment]
@abbradar Does that fix the matplotlib problem?

**Comment by CMCDragonkai** [comment]
@abbradar When attempting to use the nixpkgs-unstable to acquire tensorflowWithCuda, this results in asking for cudnn. I got the correct cudnn. But the message suggests using:

```
nix-prefetch-url file://cudnn-9.0-linux-x64-v7.tgz
```

However this doesn't work. The `nix-prefetch-url` command doesn't understand this URL. Perhaps this it is too old. But is there a more guaranteed way to do this?

**Comment by abbradar** [comment]
@CMCDragonkai I haven't tried it with matplotlib; I'll do it later tomorrow if you haven't already.

`--add-fixed sha256` is mentioned somewhere but usually only `nix-prefetch-url` is advertised. I hope this all just does away with new `nix` CLI which has commands for adding a file to the store.

All files added in this way will be cleaned up on the next garbage collection. Of course cuDNN the package will remain if you have something referencing it.

**Comment by CMCDragonkai** [comment]
I'll check today. Since I was compiling tensorflowWithGPU from scratch. However I have a question about automated deployment. With cudnn requiring manual download and nix store add. Is it possible for me to have the file already downloaded and then write a nix expression overriding cudnn so it just uses the one I have locally on the system?

**Comment by abbradar** [comment]
Yeah, `cudnn_cudatoolkit9 = lib.overrideDerivation cudnn_cudatoolkit9 (self: { src =./path/to/cudnn; })`

**Comment by CMCDragonkai** [comment]
Hey @abbradar I found out that is in fact possible to fetch cuDNN software automatically:

https://gist.github.com/CMCDragonkai/02ebcb6a5cdadcbdf6bc4ee15dac6f1b

Example:

```
# 7.0.5
wget 'https://developer.download.nvidia.com/compute/redist/cudnn/v7.0.5/cudnn-9.0-linux-x64-v7.tgz'
wget 'https://developer.download.nvidia.com/compute/redist/cudnn/v7.0.5/cudnn-9.1-linux-x64-v7.tgz'
# 7.1.4
wget 'https://developer.download.nvidia.com/compute/redist/cudnn/v7.1.4/cudnn-9.0-linux-x64-v7.1.tgz'
wget 'https://developer.download.nvidia.com/compute/redist/cudnn/v7.1.4/cudnn-9.2-linux-x64-v7.1.tgz'
```

The links don't appear to be documented officially, but I found it somewhere else, and it has been working since August 2017. If this were to keep working, perhaps we can avoid needing the user to sign up to acquire the software and just download it directly?
