### ISSUE TITLE
Tensorflow crashes on GPU

### ISSUE THREAD

**Issue by jyp** [NixOS/nixpkgs#67257]
**Describe the bug**

When trying to run a tensorflow program on GPU, I get the following error:
```
tensorflow/stream_executor/cuda/cuda_driver.cc:175] Check failed: err == cudaSuccess || err == cudaErrorInvalidValue Unexpected CUDA error: unknown error
Aborted (core dumped)
```
**To Reproduce**
- Using nix-shell master from today:
- LD_PRELOAD=/lib64/libcuda.so.1:/lib64/libnvidia-fatbinaryloader.so.418.74 python
- run tensorflow program

**Expected behavior**
No crash.

**Additional context**
This was tested on master from yesterday.

The machine is not a nixos machine, see below.

I am also seeing the same behaviour with pytorch. I am expecting that somehow a wrong version of a library is loaded. But I do not know how to figure out the mismatch.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.17-200.fc29.x86_64, Fedora, 29 (Server Edition)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`

(Not copying the irrelevant nix channels).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jyp** [comment]
When using the `tensorflow-bin` package the issue does not occur -- there is also no need to specify `LD_PRELOAD`.

**Comment by c00w** [comment]
Have you tried running without LD_PRELOAD? tensorflow should have been fixed to work without it (and was a few weeks ago).

**Comment by jyp** [comment]
@c00w Sure did. Without LD_PRELOAD, cuda does not find any GPU.

**Comment by jyp** [comment]
@yorickvP  @timokau @abbradar Have any of you tried to run tensorflow programs on GPU after #64716 ?

**Comment by abbradar** [comment]
I'm on this problem right now, the issue seems to be that CUDA drivers require LD_LIBRARY_PATH to be set in Nvidia drivers (this behavior has changed recently). I'm testing whether it helps; will make PR. 

On September 1, 2019 10:19:37 AM GMT+03:00, Jean-Philippe Bernardy <notifications@github.com> wrote:
>@yorickvP  @timokau @abbradar Have any of you tried to run tensorflow
>programs on GPU after #64716 ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/issues/67257#issuecomment-526894023

-- 
Nikolay.

**Comment by jyp** [comment]
Thanks!

**Comment by abbradar** [comment]
The problem on NixOS was actually a different one from what you described - I cannot reproduce yours and it works for me. Maybe it's a case of tensorflow linking to something tensorflow-bin avoids; I'll check this.

**Comment by jyp** [comment]
Ok, thanks.

Again FWIW the same problem occurs with pytorch. It seems that some incompatible version of a library is found when using the LD_PRELOAD trick to point to the cuda library which comes with the host OS. Unfortunately the problem manifests itself with a very poor error message ("unknown error") so I am not sure what to do.

**Comment by abbradar** [comment]
I checked linkage but didn't notice anything strange.

What is `libnvidia-fatbinaryloader.so`?

**Comment by jyp** [comment]
As far as I can tell this is the interface to the kernel module. (You'll notice it is suffixed with the driver version).

**Comment by abbradar** [comment]
The only interesting thing that I noticed is that `tensorflow-bin` has nvidia drivers from nixpkgs in its RPATH, which is _not_ right.

**Comment by jyp** [comment]
Interesting. I suppose that this is what makes it work then, since loading the driver from the host OS always results in a crash.

**Comment by abbradar** [comment]
Can you try removing it? Specifically, `nvidia_x11` from RPATH in `tensorflow-bin` expression.

**Comment by coreyoconnor** [comment]
With `nixos-unstable` I am able to use GPUs (nvidia) with `tensorflowWithCuda`. 

I do use a customized build of tensorflowWithCuda and jupyter service but I don't think those should matter. Copied here in case:

* https://github.com/coreyoconnor/nix_configs/blob/master/nixpkgs-config/overlays/tensorderp.nix#L19
* https://github.com/coreyoconnor/nix_configs/blob/master/tensorderp.nix

**Comment by c00w** [comment]
We should likely close this. I believe it has been fixed.

**Comment by timokau** [comment]
@jyp if this is still an issue I'll reopen.
